/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.MembroDAO;
import Modelo.Membro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Desenvolvimento
 */
public class TelaAniversariantes extends javax.swing.JDialog {

    /**
     * Creates new form TelaAniversariantes
     */
    public Membro conultaMembro;
    
    public TelaAniversariantes(JDialog dialogo, boolean modal) {
        super(dialogo,modal);
        initComponents();
        Tipo();
        setLocationRelativeTo(null);
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        btnDetalhes = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtData1 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Aniversáriantes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTA DE ANIVERSÁRIANTES"));

        tblDados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cargo", "Data de Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDados);
        if (tblDados.getColumnModel().getColumnCount() > 0) {
            tblDados.getColumnModel().getColumn(1).setMinWidth(250);
            tblDados.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblDados.getColumnModel().getColumn(1).setMaxWidth(250);
            tblDados.getColumnModel().getColumn(2).setMinWidth(130);
            tblDados.getColumnModel().getColumn(2).setPreferredWidth(130);
            tblDados.getColumnModel().getColumn(2).setMaxWidth(130);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnDetalhes.setText("DETALHES");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o Tipo de Filtro"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de Filtro");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "DATA", "NOME", "INTERVALO" }));
        comboFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFiltroItemStateChanged(evt);
            }
        });
        jPanel3.add(comboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, 101, 25));

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipo.setText("Selecione a data");
        jPanel3.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 27, 240, -1));
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 50, 240, 27));

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setToolTipText("Data Inicial");
        jPanel3.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 50, 115, 27));

        try {
            txtData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData1.setToolTipText("Data Final");
        jPanel3.add(txtData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 115, 27));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButton1.setText("CONULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDetalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        if (tblDados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Membro!.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        selecionar();
        dispose();
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        conultaMembro = null;
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void comboFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFiltroItemStateChanged
        Tipo();
    }//GEN-LAST:event_comboFiltroItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(comboFiltro.getSelectedIndex() == 2 && txtNome.getText().equals("")) { 
            JOptionPane.showMessageDialog(rootPane, "Preencha o nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(comboFiltro.getSelectedIndex() == 3 && txtData.getText().equals("  /  /    ") || txtData.getText().equals("  /  /    ")) { 
            JOptionPane.showMessageDialog(rootPane, "Preencha a Data Inicial e a Data Final!","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(comboFiltro.getSelectedIndex() == 1 && txtData.getText().equals("  /  /    ")) { 
            JOptionPane.showMessageDialog(rootPane, "Preencha a data!","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(comboFiltro.getSelectedIndex() == 2 && txtNome.getText() != null) {
            carregarTabelaPorBuscaAproximada();
        }
        if(comboFiltro.getSelectedIndex() == 1 && txtData != null) {
            carregarTabelaPorData();
        }
        if(comboFiltro.getSelectedIndex() == 3 && txtData.getText() != null && txtData.getText() != null) {
            try {
                carregarTabelaPorDataSelecionada();
            } catch (ParseException ex) {
                Logger.getLogger(TelaAniversariantes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDadosMouseClicked
        if (tblDados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Membro!.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        } 
    }//GEN-LAST:event_tblDadosMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void Tipo() {
        if(comboFiltro.getSelectedIndex() == 1) {
            try {
                txtData.setValue(null);
                txtData.setFocusLostBehavior(JFormattedTextField.COMMIT);
                txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
                //txtData.setToolTipText("Data Inicial");
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }

            txtData.setVisible(true);
            txtData1.setVisible(false);
            txtNome.setVisible(false);
            lblTipo.setText("Digite a data");
        } else if (comboFiltro.getSelectedIndex() == 2) {
            txtData.setVisible(true);
            txtData1.setVisible(true);
            txtNome.setVisible(true);
            lblTipo.setText("Digite o nome");
        } else if (comboFiltro.getSelectedIndex() == 3) {
            txtData.setVisible(true);
            txtData1.setVisible(true);
            txtNome.setVisible(false);
            lblTipo.setText("Data Inicial e Data Final");
        } else {
            carregarTabela();
            txtData.setVisible(false);
            txtData1.setVisible(false);
            txtNome.setVisible(false);
            lblTipo.setText("Tipo não selecionado");
        }
    }
    
    private void carregarTabela() {
        DefaultTableModel tabela = (DefaultTableModel) tblDados.getModel();
        MembroDAO dao = new MembroDAO();
        List<Membro> listaMembros = new ArrayList<>();
        listaMembros = dao.buscarTodosMembros();
        tabela.setNumRows(0);
        if(listaMembros.size() > 0) {
            btnImprimir.setEnabled(true);
        for(Membro lista : listaMembros) {
            tabela.addRow(new Object[] {lista.getNome(), lista.getCargo(), lista.getNascimento()});
           }
        } else {
            btnImprimir.setEnabled(false);
        }
    }
    
    private void carregarTabelaPorBuscaAproximada() {
        DefaultTableModel tabela = (DefaultTableModel) tblDados.getModel();
        MembroDAO dao = new MembroDAO();
        List<Membro> listaMembros = new ArrayList<>();
        listaMembros = dao.buscaAproximada(txtNome.getText());
        tabela.setNumRows(0);
        if(listaMembros.size() > 0) {
           btnImprimir.setEnabled(true);
        for(Membro lista : listaMembros) {
            tabela.addRow(new Object[] {lista.getNome(), lista.getCargo(), lista.getNascimento()});
           }
        } else {
            btnImprimir.setEnabled(false);
        }
    }
    
    private void carregarTabelaPorData() {
        DefaultTableModel tabela = (DefaultTableModel) tblDados.getModel();
        MembroDAO dao = new MembroDAO();
        List<Membro> listaMembros = new ArrayList<>();
        listaMembros = dao.buscaPorData(txtData.getText());
        tabela.setNumRows(0);
        if(listaMembros.size() > 0) {
            btnImprimir.setEnabled(true);
        for(Membro lista : listaMembros) {
            tabela.addRow(new Object[] {lista.getNome(), lista.getCargo(), lista.getNascimento()});
           }
        } else {
            btnImprimir.setEnabled(false);
        }
    }
    
    private void carregarTabelaPorDataSelecionada() throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
       
        String data = txtData.getText().substring(6,10)+"/"+txtData.getText().substring(3,5)+"/"+txtData.getText().substring(0,2);
        String data1 = txtData1.getText().substring(6,10)+"/"+txtData1.getText().substring(3,5)+"/"+txtData1.getText().substring(0,2);
        DefaultTableModel tabela = (DefaultTableModel) tblDados.getModel();
        MembroDAO dao = new MembroDAO();
        List<Membro> listaMembros = new ArrayList<>();
        listaMembros = dao.buscaPorDataSelecionada(data, data1);
        tabela.setNumRows(0);
        if(listaMembros.size() > 0) {
            btnImprimir.setEnabled(true);
        for(Membro lista : listaMembros) {
            tabela.addRow(new Object[] {lista.getNome(), lista.getCargo(), lista.getNascimento()});
           }
        } else {
            btnImprimir.setEnabled(false);
        }
    }
    
    private void selecionar() {

        int codigo = tblDados.getSelectedRow();
         String linha = (String.valueOf((String)tblDados.getValueAt(codigo, 0)));
        System.out.print(linha);

        MembroDAO dao = new MembroDAO();
        conultaMembro = dao.buscarPorParteNome(linha);
       }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        TelaAniversariantes aniversariantes = new TelaAniversariantes(new JDialog(), true);
        aniversariantes.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblDados;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtData1;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
