/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.MembroDAO;
import Modelo.Membro;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Desenvolvimento
 */
public class TelaMembros extends javax.swing.JDialog {

    /**
     * Creates new form CadastroMembro
     */
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private byte[] fotoMembro = null;
    private boolean GRAVAR = true;
    public MembroDAO dao;
    private String file = null;
    private int codigo = 0;
    
    public TelaMembros(JDialog dialogo, boolean modal) {
        super(dialogo, modal);
        initComponents();
        setLocationRelativeTo(null);
        limpaCampos();
        desabilitaCampos();
    }

    private void desabilitaCampos() {
        txtCargo.setEnabled(false);
        txtCidade.setEnabled(false);
        txtCongregacao.setEnabled(false);
        txtDataBatismo.setEnabled(false);
        txtDataExpedicao.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtDataVallidade.setEnabled(false);
        txtEstadoCivil.setEnabled(false);
        txtLocalOndeNasceu.setEnabled(false);
        txtMae.setEnabled(false);
        txtNacionalidade.setEnabled(false);
        txtNatural.setEnabled(false);
        txtNome.setEnabled(false);
        txtObservacoes.setEnabled(false);
        txtPai.setEnabled(false);
        jtxtCPF.setEnabled(false);
        jtxtRG.setEnabled(false);
        comboEstado.setEnabled(false);
    }
        private void habilitaCampos() {
        txtCargo.setEnabled(true);
        txtCidade.setEnabled(true);
        txtCongregacao.setEnabled(true);
        txtDataBatismo.setEnabled(true);
        txtDataExpedicao.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtDataVallidade.setEnabled(true);
        txtEstadoCivil.setEnabled(true);
        txtLocalOndeNasceu.setEnabled(true);
        txtMae.setEnabled(true);
        txtNacionalidade.setEnabled(true);
        txtNatural.setEnabled(true);
        txtNome.setEnabled(true);
        txtObservacoes.setEnabled(true);
        txtPai.setEnabled(true);
        jtxtCPF.setEnabled(true);
        jtxtRG.setEnabled(true);
        comboEstado.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCongregacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMae = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNatural = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtNacionalidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtRG = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtCPF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLocalOndeNasceu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtProcurar = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        txtDataExpedicao = new com.toedter.calendar.JDateChooser();
        txtDataVallidade = new com.toedter.calendar.JDateChooser();
        txtDataNascimento = new com.toedter.calendar.JDateChooser();
        txtDataBatismo = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Membros");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cargo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cidade");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Congregação de Congrega");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data da Expedição");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Data de Validade");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Pai");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mãe");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Natural");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Estado");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nacionalidade");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Data de Nascimento");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("RG");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("CPF");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Data de Batismo");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Local Onde Batizou");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Estado Cívil");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Observações");

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnFoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFoto.setText("SELECIONAR FOTO");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFoto))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(" Matricula: ");

        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("ALTERAR");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnProcurar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcurar.setText("...");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(338, 338, 338)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCargo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(txtCongregacao, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel7))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMae)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtDataExpedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDataVallidade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEstadoCivil)))
                                    .addComponent(txtCidade)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNacionalidade)))
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDataBatismo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(263, 263, 263))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(213, 213, 213)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLocalOndeNasceu, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel17))))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCongregacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataVallidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDataExpedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMae, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLocalOndeNasceu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataBatismo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       habilitaCampos();
       Novo();
       GRAVAR = true;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha o nome!","Atenção",JOptionPane.WARNING_MESSAGE);
            return;
        }
        salvarMembro();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       limpaCampos();
       Cancelar();
       GRAVAR = true;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       Sair();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        if(btnFoto.getText().equals("REMOVER FOTO")) {
            lblFoto.setIcon(null);
            fotoMembro = null;
            btnFoto.setText("SELECIONAR FOTO");
        } else {
            selecionarFoto();
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
     if(txtProcurar.getText().isEmpty() || txtProcurar.getText() == null) {
         final TelaConsultaMembro consultaMembro = new TelaConsultaMembro(this, true);
        consultaMembro.setLocationRelativeTo(consultaMembro);
        consultaMembro.setVisible(true);

        consultaMembro.addWindowListener(new java.awt.event.WindowAdapter() {
             @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Membro membro = new Membro();
                membro = consultaMembro.conultaMembro;
                if(membro != null) {
                    txtNome.setText(membro.getNome());
                    txtCargo.setText(membro.getCargo());
                    txtCidade.setText(membro.getCidade());
                    txtCongregacao.setText(membro.getCongregacao());
                    if(membro.getDataBatismo() == null) {
                        txtDataBatismo.setDate(null);
                    } else {
                    try {
                        txtDataBatismo.setDate(sdf.parse(membro.getDataBatismo()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    if(membro.getDataExpedicao() == null) {
                        txtDataExpedicao.setDate(null);
                    } else {
                    try {
                        txtDataExpedicao.setDate(sdf.parse(membro.getDataExpedicao()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    if(membro.getNascimento() == null) {
                        txtDataNascimento.setDate(null);
                    } else {
                    try {
                        txtDataNascimento.setDate(sdf.parse(membro.getNascimento()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    if(membro.getDataValidade()== null) {
                        txtDataVallidade.setDate(null);
                    } else {
                    try {
                        txtDataVallidade.setDate(sdf.parse(membro.getDataValidade()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    txtEstadoCivil.setText(membro.getEstadoCivil());
                    txtLocalOndeNasceu.setText(membro.getLocalBatismo());
                    txtMae.setText(membro.getMae());
                    txtNacionalidade.setText(membro.getNacionalidade());
                    txtNatural.setText(membro.getNatural());
                    txtObservacoes.setText(membro.getObservacoes());
                    txtPai.setText(membro.getPai());
                    jtxtCPF.setText(membro.getCpf());
                    jtxtRG.setText(membro.getRg());
                    comboEstado.setSelectedItem(membro.getEstado());
                    codigo = membro.getCodigo();
                    fotoMembro = membro.getFoto();
                    if(membro.getFoto() != null) {
                    btnFoto.setText("REMOVER FOTO");
                    Image img = (new ImageIcon(membro.getFoto())).getImage();
                    Image novaimg = img.getScaledInstance(180, 155, 4);
                    ImageIcon icon = new ImageIcon(novaimg);
                    lblFoto.setIcon(icon); 
                    } else {
                        btnFoto.setText("SELECIONAR FOTO");
                    }
                    Novo();
                    GRAVAR = false;
                }
            }
        });
     } else {
     Membro membro = new Membro();
     MembroDAO dao = new MembroDAO();
     membro = dao.buscarPorParteNome(txtProcurar.getText());
     if(membro != null) {
                    txtNome.setText(membro.getNome());
                    txtCargo.setText(membro.getCargo());
                    txtCidade.setText(membro.getCidade());
                    txtCongregacao.setText(membro.getCongregacao());
                    if(membro.getDataBatismo() == null) {
                        txtDataBatismo.setDate(null);
                    } else {
                    try {
                        txtDataBatismo.setDate(sdf.parse(membro.getDataBatismo()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    if(membro.getDataExpedicao() == null) {
                        txtDataExpedicao.setDate(null);
                    } else {
                    try {
                        txtDataExpedicao.setDate(sdf.parse(membro.getDataExpedicao()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    if(membro.getNascimento() == null) {
                        txtDataNascimento.setDate(null);
                    } else {
                    try {
                        txtDataNascimento.setDate(sdf.parse(membro.getNascimento()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    if(membro.getDataValidade()== null) {
                        txtDataVallidade.setDate(null);
                    } else {
                    try {
                        txtDataVallidade.setDate(sdf.parse(membro.getDataValidade()));
                    } catch (ParseException ex) {
                        Logger.getLogger(TelaMembros.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
                    txtEstadoCivil.setText(membro.getEstadoCivil());
                    txtLocalOndeNasceu.setText(membro.getLocalBatismo());
                    txtMae.setText(membro.getMae());
                    txtNacionalidade.setText(membro.getNacionalidade());
                    txtNatural.setText(membro.getNatural());
                    txtObservacoes.setText(membro.getObservacoes());
                    txtPai.setText(membro.getPai());
                    jtxtCPF.setText(membro.getCpf());
                    jtxtRG.setText(membro.getRg());
                    comboEstado.setSelectedItem(membro.getEstado());
                    codigo = membro.getCodigo();
                    fotoMembro = membro.getFoto();
                    if(membro.getFoto() != null) {
                    btnFoto.setText("REMOVER FOTO"); 
                    Image img = (new ImageIcon(membro.getFoto())).getImage();
                    Image novaimg = img.getScaledInstance(180, 155, 4);
                    ImageIcon icon = new ImageIcon(novaimg);
                    lblFoto.setIcon(icon);
                    } else {
                        lblFoto.setIcon(null);
                        btnFoto.setText("SELECIONAR FOTO");
                    }
                    Novo();
                    GRAVAR = false;
                }
            }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void salvarMembro() {
        Membro membro = new Membro();
        membro.setCargo(txtCargo.getText());
        membro.setCidade(txtCidade.getText());
        membro.setCongregacao(txtCargo.getText());
        membro.setCpf(jtxtCPF.getText());
        if(txtDataBatismo.getDate() == null) {
            membro.setDataBatismo(null);
        } else {
            membro.setDataBatismo(sdf.format(txtDataBatismo.getDate()));
        }
        if(txtDataExpedicao.getDate() == null) {
            membro.setDataExpedicao(null);
        } else {
            membro.setDataExpedicao(sdf.format(txtDataExpedicao.getDate()));
        }
        if(txtDataVallidade.getDate() == null) {
            membro.setDataValidade(null);
        } else {
            membro.setDataValidade(sdf.format(txtDataVallidade.getDate()));
        }
        membro.setEstado(comboEstado.getSelectedItem().toString());
        membro.setEstadoCivil(txtEstadoCivil.getText());
        membro.setFoto(fotoMembro);
        membro.setLocalBatismo(txtLocalOndeNasceu.getText());
        membro.setMae(txtMae.getText());
        membro.setNacionalidade(txtNacionalidade.getText());
        if(txtDataNascimento.getDate() == null) {
            membro.setNascimento(null);
        } else {
            membro.setNascimento(sdf.format(txtDataNascimento.getDate()));
        }
        membro.setNatural(txtNatural.getText());
        membro.setNome(txtNome.getText());
        membro.setObservacoes(txtObservacoes.getText());
        membro.setPai(txtPai.getText());
        membro.setRg(jtxtRG.getText());
        membro.setCodigo(codigo);
        
        if(GRAVAR) {
            dao = new MembroDAO();
            if(dao.salvar(membro)) {
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso","Aviso",JOptionPane.INFORMATION_MESSAGE);
                limpaCampos();
                Cancelar();
            }  
        } else {
            dao = new MembroDAO();
            if(dao.alterar(membro)) {
                JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso","Aviso",JOptionPane.INFORMATION_MESSAGE);
                limpaCampos();
                Cancelar();
            }
        }
        
    }
    
    private void Novo() {
        habilitaCampos();
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        txtProcurar.setEnabled(false);
        btnProcurar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSair.setEnabled(false);
    }
    private void Salvar() {
        desabilitaCampos();
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        txtProcurar.setEnabled(true);
        btnProcurar.setEnabled(true);
        btnSair.setEnabled(true);
    }  
    private void Alterar() {
        habilitaCampos();
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtProcurar.setEnabled(false);
        btnProcurar.setEnabled(false);
        btnSair.setEnabled(false);
    }  
    private void Excluir() {
        Salvar();
    }
    private void Cancelar() {
        Salvar();
    }
    private void Procurar() {
        
    }
    private void Sair() {
        dispose();
    }
        
    private void limpaCampos() {
        txtCargo.setText("");
        txtCidade.setText("");
        txtCongregacao.setText("");
        txtDataBatismo.setDate(null);
        txtDataExpedicao.setDate(null);
        txtDataNascimento.setDate(null);
        txtDataVallidade.setDate(null);
        txtEstadoCivil.setText("");
        txtLocalOndeNasceu.setText("");
        txtMae.setText("");
        txtNacionalidade.setText("");
        txtNatural.setText("");
        txtNome.setText("");
        txtObservacoes.setText("");
        txtPai.setText("");
        jtxtCPF.setText("");
        jtxtRG.setText("");
        comboEstado.setSelectedIndex(0);
        lblFoto.setIcon(null);
        txtProcurar.setText("");
    }
    
    private void selecionarFoto() {
        JFileChooser escolherFoto = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG,PNG e BMP", new String[] {"jpg", "png", "bmp"});
        escolherFoto.setFileFilter(filtro);
        int retorno = escolherFoto.showOpenDialog(null);
        if(retorno == 0)
        {
            file = escolherFoto.getSelectedFile().getAbsolutePath();
            Path path = Paths.get(file, new String[0]);
            try
            {
                byte tempByte[] = Files.readAllBytes(path);
                fotoMembro = tempByte;
                btnFoto.setText("REMOVER FOTO");
            }
            catch(IOException ex)
            {
                System.out.println(ex.toString());
            }
            ImageIcon im = new ImageIcon(file);
            Image img = im.getImage();
            Image novaimg = img.getScaledInstance(180, 155, 4);
            ImageIcon icon = new ImageIcon(novaimg);
            lblFoto.setIcon(icon);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        TelaMembros telaMembros = new TelaMembros(new JDialog(), true);
        telaMembros.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtCPF;
    private javax.swing.JTextField jtxtRG;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCongregacao;
    private com.toedter.calendar.JDateChooser txtDataBatismo;
    private com.toedter.calendar.JDateChooser txtDataExpedicao;
    private com.toedter.calendar.JDateChooser txtDataNascimento;
    private com.toedter.calendar.JDateChooser txtDataVallidade;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtLocalOndeNasceu;
    private javax.swing.JTextField txtMae;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNatural;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPai;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
